// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://takvthfatlcjsqgssnta.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRha3Z0aGZhdGxjanNxZ3NzbnRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjcwNTIzMzQsImV4cCI6MjA4MjYyODMzNH0.LGVh8FlYYZHy_dQtdRpU2qU4sylpNO86qRdpH8uF5U0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});